### ISSUE TITLE
circular import issue with python 3.9,  django 3.0.3, mysql, anaconda environment. 

### ISSUE THREAD

**Issue by mprati** [app-generator/django-dashboard-volt#1]
Migrations worked fine, but site dies with the following error?
Only modification made to the code is settings.py:         'ENGINE': 'django.db.backends.mysql',

Any help appreciated.
Mark

mod_wsgi (pid=52963): Failed to exec Python script file '/var/www/vhosts/django-dashboard-volt/core/wsgi.py'.
[Tue May 18 16:00:42.323978 2021] [wsgi:error] [pid 52963:tid 140392615212800] [remote 24.150.177.77:57164] mod_wsgi (pid=52963): Exception occurred processing WSGI script '/var/www/vhosts/django-dashboard-volt/core/wsgi.py'.
[Tue May 18 16:00:42.325399 2021] [wsgi:error] [pid 52963:tid 140392615212800] [remote 24.150.177.77:57164] Traceback (most recent call last):
[Tue May 18 16:00:42.325430 2021] [wsgi:error] [pid 52963:tid 140392615212800] [remote 24.150.177.77:57164]   File "/home/centos/anaconda3/envs/watchdoge_env/lib/python3.9/site-packages/MySQLdb/__init__.py", line 18, in <module>
[Tue May 18 16:00:42.325436 2021] [wsgi:error] [pid 52963:tid 140392615212800] [remote 24.150.177.77:57164]     from . import _mysql
[Tue May 18 16:00:42.325450 2021] [wsgi:error] [pid 52963:tid 140392615212800] [remote 24.150.177.77:57164] ImportError: cannot import name '_mysql' from partially initialized module 'MySQLdb' (most likely due to a circular import) (/home/centos

**Comment by app-generator** [comment]
Hello @mprati, 

Thanks for using our products. 

This is new .. We will forward the case to the `QA` and let you know if a patch was found.

**Comment by app-generator** [comment]
Hello @mprati, 

Please use the latest release **v1.0.3** and let us know if the reported issue persists. 
`Anaconda environment` is not integrated into our work queue. 

Closing for now.
